services:
  app:
    image: ${DOCKER_USERNAME}/team:latest
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=springboot
      - SPRING_DATASOURCE_PASSWORD=java1234
    depends_on:
      - oracle
    restart: unless-stopped
    networks:
      - team-network
  oracle:
    image: gvenzl/oracle-xe:18
    container_name: oracle
    ports:
      - "1522:1521"
      - "5551:5550"
    shm_size: '1g'
    environment:
      - ORACLE_PASSWORD=java1234
      - ORACLE_CHARACTERSET=AL32UTF8
      - TZ=Asia/Seoul
    volumes:
      - docker-data:/opt/oracle/oradata
      - ./script.sql:/container-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - team-network

networks:
  team-network:
    driver: bridge
     
volumes:
  docker-data:    
    

    
    
    
    
    
    
    
    
    
    
    