name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  issues: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v3
      
    - name: JDK 17 설정
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle 실행 권한 부여
      if: runner.os == 'Windows'
      run: |
        attrib +x gradlew
      shell: cmd
      
    - name: Gradle 실행 권한 부여
      if: runner.os != 'Windows'
      run: chmod +x ./gradlew
        
    - name: 단위 테스트 실행
      run: ./gradlew test --no-daemon
      
    - name: 단위 테스트 실패 시 이슈 생성하기      if: failure()
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/TEST_FAILURE_TEMPLATE.md
        assignees: ${{ github.actor }}
        
    - name: Gradle 빌드
      run: ./gradlew clean build
        
    - name: Docker 로그인
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Docker 이미지 빌드 및 푸시
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/team:latest
        
  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      # EC2에 SSH 접속해서 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 퍼블릭 IP
          username: ${{ secrets.EC2_USER }} # EC2 계정 > ubuntu
          key: ${{ secrets.EC2_SSH_KEY }} # EC2 계정 > *.pem
          script: |
          
            # 이제부터 행동은 EC2에서 실행된다.
            
            # 기존 컨테이너 중지 및 삭제
            sudo docker stop myapp || true
            sudo docker rm myapp || true

            # 새 이미지 받기
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/team:latest

            # 새 컨테이너 실행
            sudo docker run -d \
              --name myapp \
              -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/team:latest

            # 안 쓰는 이미지 정리
            sudo docker image prune -f
        
        
        
        
        
        
        